on:
    push:
        branches:
            - main
name: 🚀 Deploy website on push
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v3

    - name: Use Node.js 18
      uses: actions/setup-node@v2
      with:
        node-version: '18'
      
    - name: 🔨 Build Project
      run: |
        npm install
        npm run build
      
    # - name: Upload artifact
    #   uses: actions/upload-pages-artifact@v1
    #   with:
    #     # Upload dist repository
    #     path: './dist'
    
    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@v4.3.4
      with:
        server: ${{ secrets.GIT_CPANEL_FTP_SERVER }}
        protocol: ${{ secrets.GIT_CPANEL_FTP_PROTOCOL }}
        username: ${{ secrets.GIT_CPANEL_FTP_USERNAME }}
        password: ${{ secrets.GIT_CPANEL_FTP_PASSWORD }}
        port: ${{ secrets.GIT_CPANEL_FTP_PORT }}
        server-dir: /oreegi.com/
        local-dir: './dist/'
        exclude: |
          **/.git*
          **/.git*/**
          **/node_modules/**
          .eslintrc.cjs
          .gitignore